repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.4.0'
  hooks:
  - id: check-yaml
    exclude: ^\.deploy/helm/app/templates/.*\.(yml|yaml)
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: '23.1.0'
  hooks:
  - id: black
    language_version: python3.12
- repo: https://github.com/pycqa/isort
  rev: '5.12.0'
  hooks:
  - id: isort
    name: isort (python)
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system  # the language of the hook - tells pre-commit how to install the hook.
      types: [python]
      files: ^shroombot/
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
    - id: pyright
      name: pyright
      entry: pyright
      language: node  # pyright depends on nodejs
      files: ^shroombot/
      require_serial: true
      types: [python]
